import { Link } from "react-router-dom";
import LegalLayout, { LEGAL_ENTITY, PRIVACY_EMAIL } from "./LegalLayout";

/**
 * Public privacy policy (Google Play listing + in-app link).
 * Content reflects what the web, desktop and Android clients actually
 * collect; review with counsel before changing data practices.
 */
export default function PrivacyPolicy() {
    return (
        <LegalLayout title="Privacy Policy">
            <p>
                AINO is a workforce platform that organisations ("your employer" or "the
                customer") use for attendance, leave, tasks, chat, calls, meetings,
                calendar, notes and payroll self-service. This policy explains what
                personal data the AINO web, desktop and Android apps process, why, and
                the choices you have. It is issued by {LEGAL_ENTITY} ("AINO", "we").
            </p>

            <h2>1. Who is responsible for your data</h2>
            <p>
                Your employer decides to use AINO, creates your account and decides which
                features are switched on. For workplace data your employer is the data
                fiduciary (controller) and AINO processes that data on its behalf under
                our customer agreement. AINO is the data fiduciary only for the limited
                data we need to run, secure and support the service (for example
                security logs and crash reports).
            </p>

            <h2>2. Data we process</h2>
            <table>
                <thead>
                    <tr><th>Category</th><th>Examples</th><th>When</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Account and profile</td>
                        <td>Name, username, work email, role, department, manager, profile photo</td>
                        <td>Created by your employer; you may edit some fields</td>
                    </tr>
                    <tr>
                        <td>Attendance</td>
                        <td>Clock-in/out and break times, work mode, timezone offset</td>
                        <td>When you use attendance</td>
                    </tr>
                    <tr>
                        <td>Precise location</td>
                        <td>Latitude, longitude and accuracy at the moment you clock in, and distance to the office</td>
                        <td>Only when you clock in and your employer has turned on office verification. AINO does not track location in the background</td>
                    </tr>
                    <tr>
                        <td>Office Wi-Fi</td>
                        <td>The identifier (BSSID) of the Wi-Fi network you are connected to</td>
                        <td>Only at clock-in, when your employer uses Wi-Fi verification</td>
                    </tr>
                    <tr>
                        <td>Face verification</td>
                        <td>A numeric face template (128 numbers), not a photo, and a match score</td>
                        <td>Only if you enrol and your employer requires face verification. You can remove your template at any time from your profile</td>
                    </tr>
                    <tr>
                        <td>Work content</td>
                        <td>Tasks, comments, leave requests, calendar events, notes, files you upload</td>
                        <td>When you create or receive them</td>
                    </tr>
                    <tr>
                        <td>Messages and calls</td>
                        <td>Chat messages, attachments, voice notes, reactions, read receipts, call history (who, when, how long)</td>
                        <td>When you use chat, calls or meetings. Call audio and video are transmitted live and are not recorded unless a meeting host starts a broadcast</td>
                    </tr>
                    <tr>
                        <td>Payroll self-service</td>
                        <td>Salary slips your employer publishes to you</td>
                        <td>If your employer uses payroll</td>
                    </tr>
                    <tr>
                        <td>Device and technical</td>
                        <td>Device identifier generated by the app, push notification token, app version, OS version, IP address, sign-in times</td>
                        <td>To keep you signed in, deliver notifications and secure your account</td>
                    </tr>
                    <tr>
                        <td>Diagnostics</td>
                        <td>Crash reports and stack traces (Android), without message content</td>
                        <td>When the app crashes</td>
                    </tr>
                </tbody>
            </table>
            <p>
                The Android app asks for camera, microphone, photos, notifications and
                location permissions only when you use a feature that needs them. You can
                withdraw a permission in your device settings at any time.
            </p>

            <h2>3. Why we use it</h2>
            <ul>
                <li>To provide the features your employer has enabled.</li>
                <li>To verify attendance where your employer requires it.</li>
                <li>To send notifications about messages, calls, approvals and tasks.</li>
                <li>To secure accounts, prevent abuse and investigate incidents.</li>
                <li>To fix bugs and keep the service reliable.</li>
            </ul>
            <p>
                We do not sell personal data, do not use it for advertising and do not
                use your workplace content to train AI models.
            </p>

            <h2>4. Who we share it with</h2>
            <ul>
                <li>Your employer and the colleagues your employer's settings allow.</li>
                <li>
                    Service providers that host or deliver the service for us: cloud hosting
                    and databases (Railway), content delivery and file storage (Cloudflare),
                    push notifications and crash reporting (Google Firebase), and email
                    delivery. They may only process data on our instructions.
                </li>
                <li>Authorities, where the law requires it.</li>
            </ul>

            <h2>5. Where and how long we keep it</h2>
            <p>
                Data is stored with our hosting providers and may be processed outside
                India where they operate, with contractual safeguards. Each organisation's
                data is kept in a separate database. We keep workplace data for as long as
                your employer's account is active or your employer instructs. Expired
                sessions and old security logs are deleted automatically. When an
                organisation leaves AINO its data is deleted after the retention period in
                the customer agreement.
            </p>

            <h2>6. Security</h2>
            <p>
                Data is encrypted in transit (HTTPS/TLS). Sign-in tokens on Android are
                encrypted with a key held in the Android Keystore. Access is limited by
                role, and administrative functions are only available on the web and
                desktop apps.
            </p>

            <h2>7. Your rights</h2>
            <p>
                Under the Digital Personal Data Protection Act, 2023 and other applicable
                laws you may ask to access, correct or erase your personal data, withdraw
                consent, and nominate someone to exercise your rights. Because your
                employer controls most workplace data, we may forward your request to
                them. You can delete your own account in the app (Profile → Edit Profile
                → Delete My Account) or as described on the{" "}
                <Link to="/account-deletion">account deletion page</Link>.
            </p>

            <h2>8. Children</h2>
            <p>AINO is a workplace service and is not intended for anyone under 18.</p>

            <h2>9. Contact and grievances</h2>
            <p>
                Grievance Officer, {LEGAL_ENTITY}:{" "}
                <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>. We aim to respond
                within 30 days. If you are not satisfied you may complain to the Data
                Protection Board of India.
            </p>

            <h2>10. Changes</h2>
            <p>
                We will post updates on this page and change the "Last updated" date.
                Significant changes will be announced in the app.
            </p>
        </LegalLayout>
    );
}
